### ISSUE TITLE
 `cannot read property 'file' of undefined` errors when project uses Babel 7

### ISSUE THREAD

**Issue by sltenorio99** [dvajs/babel-plugin-dva-hmr#14]
After an upgrade of a work project Babel 7, we experienced `cannot read property 'file' of undefined` errors with this plugin and webpack wouldn't compile.

Proposed Fix: #13

**Comment by vagusX** [comment]
any progress on this issue?

**Comment by ferhatelmas** [comment]
@sorrycc do you have any ETA for reviewing fix ?

**Comment by YanYuanFE** [comment]
解决办法：安装@babel/plugin-transform-runtime
配置babelrc：
{
  "presets":["@babel/react", "@babel/env"],
  "plugins": [
    "dva-hmr",
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-transform-runtime",
    [
      "import", {
        "libraryName": "antd",
//        "libraryDirectory": "es",
        "style": true
      }
    ]
  ]
}`
`

**Comment by loganfsmyth** [comment]
Would someone be able to make a reproducible example and and let us know in https://github.com/babel/babel/issues/8641 ? This seems like an accidental breakage in Babel 7's code.

**Comment by dickeylth** [comment]
@sorrycc 这个模块还在维护么？babel 7 都已经出了 一年了……
