### ISSUE TITLE
webpack搭建的dva项目，应该如何正确使用 dva-hmr

### ISSUE THREAD

**Issue by Liuqing650** [dvajs/babel-plugin-dva-hmr#19]
使用的webpack.config.js 配置的dva 项目，有在 `.babelrc` 里面配置 `dva-hmr`(没有使用 .roadhog 进行配置，直接使用的 webpack@3.10.0)

但是实际开发时只走了 `webpack` 默认的热替换，并没有走 `dva-hmr`，使得修改 `./models/*.js` 下的文件时会报如下错误
```js
index.js:2178 Unexpected key "home" found in preloadedState argument passed to createStore. 
Expected to find one of the known reducer keys instead: "routing", "@@dva". Unexpected keys will be ignored.
```
有没有可能提供一种正确的使用方法呢？

**配置文件**

`.babelrc` 文件配置如下
```json
{
  "presets": [
    "react",
    "stage-0",
    "es2015"
  ],
  "comments": true,
  "plugins": [
    "add-module-exports",
    "syntax-dynamic-import",
    "transform-decorators-legacy",
    [
      "import",
      {
        "libraryName": "antd",
        "libraryDirectory": "es",
        "style": true
      }
    ],
    [
      "transform-class-properties",
      {
        "spec": true
      }
    ]
  ],
  "env": {
    "development": {
      "plugins": [
        "dva-hmr",
        "transform-runtime"
      ]
    }
  }
}
```
`webpack` 配置

```js
devServer: {
    contentBase: path.join(__dirname, "public"),
    compress: true,
    historyApiFallback: true, 
    hot: true,
    quiet: true,
    overlay: true
  },
```

**Comment by Liuqing650** [comment]
已经找到解决方式了，
删除 `babel-plugin-dva-hmr` 使用 `react-hot-loader` 替代即可

**Comment by MillionQW** [comment]
@Liuqing650 想问问使用 react-hot-loader 后有什么文件需要配置吗

**Comment by Liuqing650** [comment]
@MillionQW 不需要额外的配置，在使用过程中我最终还是去掉了hmr，`react-hot-loader` 和 `react-loadable` 在 `dva` 环境里面会随着产生的页面增多，生成大量的 `hot-update.json` 最终导致页面反应迟钝， 可以查看这个配置： [hmr config](https://github.com/Liuqing650/webpack-antd/blob/master/src/index.js)

```jsx
// 放在 index.js 或者入口那里都能运行， 同时产生的问题一样的
if (module.hot) {
    module.hot.accept();
 }
```

如果你有好的解决方式不妨分享一下，我也学习学习 :）

**Comment by MillionQW** [comment]
@Liuqing650 哈哈感谢你的回复，留言后我进去你的主页看了你的项目，照着那个配了，但还是有保存后状态丢失的问题，可能因为我没有用 ```react-loadable```，我加一下试试。
你不使用 hmr 点保存的时候不会有状态丢失的问题吗？

**Comment by Liuqing650** [comment]
@MillionQW 状态丢失是什么状态？

**Comment by MillionQW** [comment]
@Liuqing650 就比如 dva 里保存着 username，修改代码后点击保存，浏览器就报错
```
Cannot read property 'username' of undefined
```

**Comment by Liuqing650** [comment]
@MillionQW 那个问题我也遇到过，不过似乎快遗忘了
dva-hmr中似乎对每一次热替换都两次require其中的modle. 
1. 先注销 app里面的旧 modle, [unmodel](https://github.com/dvajs/dva/blob/a3af9c7f2b6b1a64af750aa29c672934503eff71/packages/dva/index.d.ts#L94)
2. 再require一次新的model并注册到app里面

这两步也就说明了你修改了 `model` 中的内容， app 中缓存的 model 数据和 hmr 的根本不一致， dva 面对不一致的问题，估计就干脆  unmodel 了这个 model,  也就导致页面找不到那玩意了吧， dva 的源码没去看过，如果这个用不了，不如用 `mobx` 吧 >_<

```jsx
// babel-plugin-dva-hmr/blob/master/src/index.js
if (module.hot) {
    const modelNamespaceMap = {};
    let model = require('${modelPath}');
    if (model.default) model = model.default;
    modelNamespaceMap['${modelPath}'] = model.namespace;
    module.hot.accept('${modelPath}', () => {
      try {
        app.unmodel(modelNamespaceMap['${modelPath}']);
        let model = require('${modelPath}');
        if (model.default) model = model.default;
        app.model(model);
      } catch(e) { console.error(e); }
    });
  }
```

我创建的项目能够hmr页面和modle， 得益于 `react-hot-loader` 吧， 这个插件不得不说做的真的很棒. 和 react-loadable 没有任何关系，即使我去掉，依然可以执行
