### ISSUE TITLE
entries 参数的疑问

### ISSUE THREAD

**Issue by CodingMonkeyzh** [dvajs/babel-plugin-dva-hmr#2]
我在 `webpack.config.js` 中对 hmr 的配置如下：

```
webpackConfig.babel.plugins.push(['dva-hmr', {
      entries: [
        './src/index.js',
        './src/login.js',
      ],
      container: '#root',
      quiet: false,
    }]);
```

因为多个入口文件的存在，所以我在 `entries` 写入了两个路径。但是最终的效果只有写在第一个位置的生效了， 达到了不刷新页面更新DOM的效果，后面的入口文件对应的页面每次修改完页面还是会刷新。
请问这是怎么一回事？谢谢！

**Comment by sorrycc** [comment]
0.2.0 已经不需要配 `entries` 了。

**Comment by CodingMonkeyzh** [comment]
果然， 我本地的版本是 0.1.0，更新 0.2.0 之后这个问题不存在了，看来 `container` 和 `quiet` 这两个参数是 0.2.0 版本的。 谢谢！
