### ISSUE TITLE
ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by masterzh01** [dvajs/babel-plugin-dva-hmr#8]
Hi，

出现错误 http://127.0.0.1:8000/__webpack_hmr net::ERR_CONNECTION_REFUSED

listen address 如何更改？谢谢

**Comment by sorrycc** [comment]
服务器已关闭?

**Comment by masterzh01** [comment]
server 运行在虚拟机里面，在外面去访问时hmr不能工作。

它默认连接的是localhost，有没有办法指定虚拟机的地址？

**Comment by sorrycc** [comment]
目前不行，写死了 https://github.com/dora-js/dora-plugin-webpack-hmr/blob/master/src/index.js#L28 。

两个方案：

1. 找到 node_modules/dora-plugin-webpack-hmr 下的对应文件，修改 127.0.0.1 为对应 IP
2. 切换工具到 roadhog，没有写死 ip，https://github.com/sorrycc/blog/issues/17 最下面有修改步骤

**Comment by masterzh01** [comment]
OK

明白，谢谢。
